### ISSUE TITLE
Can't build, any help appreciated!

### ISSUE THREAD

**Issue by ghost** [toddway/FeedRead#1]
Thanks for creating this project! I've made some progress, but I'm not sure how to get over this error:

20:12:46.004 [ERROR] [org.gradle.BuildExceptionReporter] 
20:12:46.007 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:12:46.008 [ERROR] [org.gradle.BuildExceptionReporter] 
20:12:46.009 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
20:12:46.009 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
20:12:46.010 [ERROR] [org.gradle.BuildExceptionReporter] > Cannot evaluate module data : Cannot evaluate module core : Cannot evaluate module shelf : Configuration with name 'default' not found.
20:12:46.011 [ERROR] [org.gradle.BuildExceptionReporter] 
20:12:46.012 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
20:12:46.014 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
20:12:46.014 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
20:12:46.015 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
20:12:46.016 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
20:12:46.020 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
20:12:46.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
20:12:46.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
20:12:46.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
20:12:46.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
20:12:46.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
20:12:46.023 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
20:12:46.023 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
20:12:46.023 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
20:12:46.023 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
20:12:46.024 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
20:12:46.024 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
20:12:46.024 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
20:12:46.025 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
20:12:46.025 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
20:12:46.025 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
20:12:46.026 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
20:12:46.026 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
20:12:46.027 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
20:12:46.027 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
20:12:46.028 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
20:12:46.028 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
20:12:46.029 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.doAction(Main.java:33)
20:12:46.029 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
20:12:46.030 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
20:12:46.030 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
20:12:46.031 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
20:12:46.031 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
20:12:46.031 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
20:12:46.032 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
20:12:46.032 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module data : Cannot evaluate module core : Cannot evaluate module shelf : Configuration with name 'default' not found.
20:12:46.033 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:645)
20:12:46.033 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:232)
20:12:46.033 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:133)
20:12:46.034 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:272)
20:12:46.034 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:591)
20:12:46.034 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:588)
20:12:46.035 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
20:12:46.035 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.Recorder$record.call(Unknown Source)
20:12:46.035 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:69)
20:12:46.036 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:587)
20:12:46.036 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:690)
20:12:46.036 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:452)
20:12:46.037 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:271)
20:12:46.037 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy:448)
20:12:46.037 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy)
20:12:46.038 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
20:12:46.038 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
20:12:46.038 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
20:12:46.039 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:447)
20:12:46.039 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:388)
20:12:46.039 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
20:12:46.040 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
20:12:46.040 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
20:12:46.040 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
20:12:46.041 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$_createTasks_closure13.doCall(BasePlugin.groovy:387)
20:12:46.041 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
20:12:46.042 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
20:12:46.042 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
20:12:46.042 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
20:12:46.043 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
20:12:46.043 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
20:12:46.043 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
20:12:46.044 [ERROR] [org.gradle.BuildExceptionReporter]    ... 31 more
20:12:46.044 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module core : Cannot evaluate module shelf : Configuration with name 'default' not found.
20:12:46.044 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:645)
20:12:46.044 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:643)
20:12:46.045 [ERROR] [org.gradle.BuildExceptionReporter]    ... 62 more
20:12:46.045 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module shelf : Configuration with name 'default' not found.
20:12:46.045 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:645)
20:12:46.045 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:643)
20:12:46.046 [ERROR] [org.gradle.BuildExceptionReporter]    ... 63 more
20:12:46.046 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
20:12:46.046 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:79)
20:12:46.046 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:192)
20:12:46.047 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:69)
20:12:46.047 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:33)
20:12:46.047 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:69)
20:12:46.047 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
20:12:46.048 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:643)
20:12:46.048 [ERROR] [org.gradle.BuildExceptionReporter]    ... 64 more
20:12:46.048 [ERROR] [org.gradle.BuildExceptionReporter] 
20:12:46.048 [LIFECYCLE] [org.gradle.BuildResultLogger] 
20:12:46.049 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
20:12:46.049 [LIFECYCLE] [org.gradle.BuildResultLogger]

**Comment by feliu** [comment]
+1
